name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Dotnet Publish
      run: dotnet publish DemoBank.API -c Release -o deploy-web -r linux-x64

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.REMOTE_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace

    - name: Deploy with rsync
      run: |
        rsync -avz -e "ssh -p ${{ secrets.REMOTE_PORT }}" \
        ./deploy-web/ \
        ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/www/wwwroot/bank-api.techmsg.dev/

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          sudo /www/server/panel/pyenv/bin/supervisorctl restart bankapi:*

    - name: Cleanup
      if: always()
      run: rm -rf ~/.ssh 
